DELETE FROM Ethnicity
DBCC CHECKIDENT ('ethnicity', RESEED, 0)

DELETE FROM City
DBCC CHECKIDENT ('City', RESEED, 0)

DELETE FROM Gender
DBCC CHECKIDENT ('Gender', RESEED, 0)

DELETE FROM Occupation
DBCC CHECKIDENT ('Occupation', RESEED, 0)

DELETE FROM Outcome
DBCC CHECKIDENT ('Outcome', RESEED, 0)

DELETE FROM Symptom
DBCC CHECKIDENT ('Symptom', RESEED, 0)